site_name:  Amazon ETL Train-The-Trainer Workshop
repo_name: "vfreitas23/aws-etl-ttt-workshop"
repo_url: "https://github.com/vfreitas23/aws-etl-ttt-workshop"
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
nav:
  - Introduction: '000-Intro/intro.md'
  - Part 0:
    - Pre Steps: '00-PreSteps/pre-steps.md'
  - Part 1:
    - TPCDS & RDS MySQL Lab: '01-MySQL-TPCDS/mysql-tpcds.md'
  - Part 2:
    - GLUE DATABASE, TABLES, CONNECTIONS, CRAWLERS, CLASSIFIERS: '02-GlueComponentsLab/glue-components-lab.md'
  - Part 3:
    - GLUE (STUDIO) STREAMING: '03-StreamingLab/streaming-lab.md'
  - Part 4:
    - ORCHESTRATION & DATA ANALYSIS: '04-OrchestrationLab/orchestration-lab.md'
  - Part 5:
    - DATA QUALITY & PREPARATION WITH AWS GLUE DATABREW: '05-DataBrewLab/databrew-lab.md'
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - attr_list
    - md_in_html
